source 'https://rubygems.org'

# Web framework
gem 'rails', '~> 7.1.5'
gem 'puma', '~> 6.5'

# Database
gem 'pg', '~> 1.5'
gem 'redis', '~> 5.0'

# Background jobs
gem 'sidekiq', '~> 7.3'

# API
gem 'jbuilder', '~> 2.11'
gem 'rack-cors'

group :development, :test do
  gem 'rspec-rails', '~> 6.0'
  gem 'factory_bot_rails'
  gem 'faker'
end

group :development do
  gem 'rubocop', '~> 1.72', require: false
  gem 'rubocop-rails', '~> 2.30', require: false
end

