// Package cache provides a minimal caching interface for the pipeline.
//
// The cache abstraction allows different storage backends:
//   - File-based (CLI)
//   - In-memory (testing)
//   - Redis (cloud platform - implemented in stacktower-cloud)
//
// The cache is used to store:
//   - HTTP responses from package registries
//   - Parsed dependency graphs
//   - Computed layouts
//   - Rendered artifacts
//
// Cache keys are opaque strings generated by implementations.
// The pipeline doesn't need to know about key structure, scoping, or TTLs.
package cache

import (
	"context"
	"time"
)

// Cache TTL constants for different artifact types.
// These define how long cached items remain valid before expiring.
const (
	TTLGraph        = 7 * 24 * time.Hour  // 1 week - dependency graphs change with new versions
	TTLLayout       = 30 * 24 * time.Hour // 30 days - layouts are stable once computed
	TTLArtifact     = 90 * 24 * time.Hour // 90 days - rendered artifacts rarely need regeneration
	TTLHTTPResponse = 24 * time.Hour      // 1 day - registry API responses (used by integrations)
)

// Cache provides generic key-value caching with TTL support.
// All methods must be safe for concurrent use.
type Cache interface {
	// Get retrieves a value by key.
	// Returns (data, true, nil) on hit.
	// Returns (nil, false, nil) on miss or expiration.
	// Returns (nil, false, err) on error.
	Get(ctx context.Context, key string) ([]byte, bool, error)

	// Set stores a value with the given TTL.
	// A TTL of 0 means no expiration.
	Set(ctx context.Context, key string, data []byte, ttl time.Duration) error

	// Delete removes a value from the cache.
	// Not finding the key is not an error.
	Delete(ctx context.Context, key string) error

	// Close releases any resources held by the cache.
	Close() error
}

// Keyer generates cache keys for pipeline artifacts.
// Implementations should produce stable, collision-resistant keys.
type Keyer interface {
	// HTTPKey generates a key for HTTP response caching.
	// namespace isolates different registries (e.g., "npm:", "pypi:").
	HTTPKey(namespace, key string) string

	// GraphKey generates a key for dependency graph caching.
	GraphKey(language, pkg string, opts GraphKeyOpts) string

	// LayoutKey generates a key for layout caching.
	LayoutKey(graphHash string, opts LayoutKeyOpts) string

	// ArtifactKey generates a key for artifact caching.
	ArtifactKey(layoutHash string, opts ArtifactKeyOpts) string
}

// GraphKeyOpts defines parameters that affect graph resolution during parsing.
// Different options produce different graphs, so they're part of the cache key.
// Note: Normalization is applied during layout, not parsing, so it's not here.
type GraphKeyOpts struct {
	MaxDepth          int    `json:"max_depth"`
	MaxNodes          int    `json:"max_nodes"`
	Enriched          bool   `json:"enriched,omitempty"`           // Whether GitHub metadata enrichment was performed
	SecurityScan      bool   `json:"security_scan,omitempty"`      // Whether vulnerability scan data is included
	IncludePrerelease bool   `json:"include_prerelease,omitempty"` // Whether prerelease versions were included
	DependencyScope   string `json:"dependency_scope,omitempty"`   // Whether graph includes prod-only or all dependency groups
	RuntimeVersion    string `json:"runtime_version,omitempty"`    // Target runtime version for marker evaluation (e.g., "3.11" for Python)
}

// LayoutKeyOpts defines parameters that affect layout computation.
// Different options produce different layouts, so they're part of the cache key.
type LayoutKeyOpts struct {
	VizType   string  `json:"viz_type"`
	Width     float64 `json:"width"`
	Height    float64 `json:"height"`
	Normalize bool    `json:"normalize,omitempty"` // Whether normalization was applied
	Ordering  string  `json:"ordering,omitempty"`
	Merge     bool    `json:"merge,omitempty"`
	Randomize bool    `json:"randomize,omitempty"`
	Seed      uint64  `json:"seed,omitempty"`
}

// ArtifactKeyOpts defines parameters that affect artifact rendering.
// Different options produce different artifacts, so they're part of the cache key.
//
// IMPORTANT: This must include ALL options that affect rendering output:
//   - Format: Output format (svg/png/pdf)
//   - Style: Visual style (simple/handdrawn) - affects SVG structure
//   - ShowEdges: Show dependency edges - adds <line> elements
//   - Popups: Hover popups - adds metadata to SVG
//   - Nebraska: Maintainer ranking - adds panel to visualization
//   - Merge: Edge filtering for subdividers - affects which edges render
//   - Normalize: Whether graph was normalized - changes node/edge count
//   - ShowVulns: Whether vulnerability colours are rendered
//
// When adding new render-time options to pipeline.Options, update this struct!
type ArtifactKeyOpts struct {
	Format       string `json:"format"`
	Style        string `json:"style,omitempty"`
	ShowEdges    bool   `json:"show_edges,omitempty"`
	Popups       bool   `json:"popups,omitempty"`
	Nebraska     bool   `json:"nebraska,omitempty"`
	Merge        bool   `json:"merge,omitempty"`
	Normalize    bool   `json:"normalize,omitempty"`
	ShowVulns    bool   `json:"show_vulns,omitempty"`
	ShowLicenses bool   `json:"show_licenses,omitempty"`
	FlagsOnTop   bool   `json:"flags_on_top,omitempty"`
}

// DefaultKeyer provides a simple hash-based key generation strategy.
type DefaultKeyer struct{}

// NewDefaultKeyer creates a default keyer.
func NewDefaultKeyer() Keyer {
	return &DefaultKeyer{}
}

// HTTPKey generates a key for HTTP response caching.
func (k *DefaultKeyer) HTTPKey(namespace, key string) string {
	return "http:" + namespace + ":" + key
}

// GraphKey generates a key for dependency graph caching.
func (k *DefaultKeyer) GraphKey(language, pkg string, opts GraphKeyOpts) string {
	return hashKey("graph", language, pkg, opts)
}

// LayoutKey generates a key for layout caching.
func (k *DefaultKeyer) LayoutKey(graphHash string, opts LayoutKeyOpts) string {
	return hashKey("layout", graphHash, opts)
}

// ArtifactKey generates a key for artifact caching.
func (k *DefaultKeyer) ArtifactKey(layoutHash string, opts ArtifactKeyOpts) string {
	return hashKey("artifact", layoutHash, opts)
}
